### ISSUE TITLE
Doesn't work with Intellij 2026.2.2

### ISSUE THREAD

**Issue by guttormvikquorum** [redhat-developer/intellij-rsp#161]
[kind/bug]

## What versions of software are you using?
- Operating System: Windows 11
- IntelliJ version: 2026.2.2
- Intellij-rsp extension version: 0.8.1.Final.122

## What did you run exactly?

- "Create Server" gives "No server found in the given folder
- "Download Server" gives dialog with "Error loading license text.", so I don't know what I'm accepting.
- "Edit Server" gives exceptions

## Any logs, error output, etc?

With telemetry ON, edit server fails with:
```
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
      at com.redhat.devtools.intellij.telemetry.core.util.FileUtils.isFileUrl(FileUtils.java:63)
      at com.redhat.devtools.intellij.telemetry.core.util.FileUtils.getPathForFileUrl(FileUtils.java:69)
      at com.redhat.devtools.intellij.telemetry.core.configuration.limits.LimitsConfigurations.readFile(LimitsConfigurations.java:70)
      at com.redhat.devtools.intellij.telemetry.core.configuration.limits.LimitsConfigurations.downloadRemote(LimitsConfigurations.java:55)
      at com.redhat.devtools.intellij.telemetry.core.configuration.limits.EventLimits.downloadRemote(EventLimits.java:163)
      at com.redhat.devtools.intellij.telemetry.core.configuration.limits.EventLimits.getAllLimits(EventLimits.java:100)
      at com.redhat.devtools.intellij.telemetry.core.configuration.limits.EventLimits.canSend(EventLimits.java:61)
      at com.redhat.devtools.intellij.telemetry.core.service.TelemetryService.doSend(TelemetryService.java:98)
      at com.redhat.devtools.intellij.telemetry.core.service.TelemetryService.sendUserInfo(TelemetryService.java:83)
      at com.redhat.devtools.intellij.telemetry.core.service.TelemetryService.send(TelemetryService.java:77)
      at com.redhat.devtools.intellij.telemetry.core.service.TelemetryMessageBuilder$TelemetryServiceFacade.send(TelemetryMessageBuilder.java:221)
      at com.redhat.devtools.intellij.telemetry.core.service.Message.send(Message.java:118)
      at com.redhat.devtools.intellij.telemetry.core.service.TelemetryMessageBuilder$ActionMessage.send(TelemetryMessageBuilder.java:156)
      at com.redhat.devtools.intellij.rsp.telemetry.TelemetryService.sendMsg(TelemetryService.java:105)
      at com.redhat.devtools.intellij.rsp.telemetry.TelemetryService.sendWithType(TelemetryService.java:91)
      at com.redhat.devtools.intellij.rsp.telemetry.TelemetryService.sendWithType(TelemetryService.java:97)
```

With telemetry OFF, edit server fails with:
```
Unhandled exception in EDT

com.intellij.openapi.diagnostic.UnhandledException: Write access is allowed inside write-action only (see Application.runWriteAction()); If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction ; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#51,AWT-EventQueue-0,10,main] 1491643958 (EventQueue.isDispatchThread()=true)
SystemEventQueueThread: (same)
      at com.intellij.openapi.application.impl.ExceptionsKt.processUnhandledException(exceptions.kt:56)
      at com.intellij.platform.ide.bootstrap.StartupErrorReporter.processException(StartupErrorReporter.java:349)
      at com.intellij.ide.IdeEventQueue.processException(IdeEventQueue.kt:476)
      at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:738)
      at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:637)
      at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:568)
      at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0$0$0$0(IdeEventQueue.kt:388)
      at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:941)
      at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0$0$0(IdeEventQueue.kt:387)
      at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$0(IdeEventQueue.kt:1122)
      at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
      at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1122)
      at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0(IdeEventQueue.kt:382)
      at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:422)
      at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
      at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
      at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
      at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
      at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
      at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Write access is allowed inside write-action only (see Application.runWriteAction()); If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction ; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#51,AWT-EventQueue-0,10,main] 1491643958 (EventQueue.isDispatchThread()=true)
SystemEventQueueThread: (same)
      at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:270)
      at com.intellij.util.concurrency.ThreadingAssertions.throwThreadAccessException(ThreadingAssertions.java:258)
      at com.intellij.util.concurrency.ThreadingAssertions.assertWriteAccess(ThreadingAssertions.java:242)
      at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.setWritable(PersistentFSImpl.java:781)
      at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.setWritable(VirtualFileSystemEntry.java:557)
      at com.redhat.devtools.intellij.rsp.actions.EditServerAction.singleSelectionActionPerformed(EditServerAction.java:61)
      at com.redhat.devtools.intellij.rsp.actions.AbstractTreeAction.actionPerformed(AbstractTreeAction.java:87)
      at com.redhat.devtools.intellij.rsp.actions.AbstractTreeAction.actionPerformed(AbstractTreeAction.java:61)
      ...
```

**Comment by robstryker** [comment]
Working on this. Thanks for the bug report :)
